# Generated by Django 5.2 on 2025-05-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_projeto', '0002_alter_professor_data_contratacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='data_termino',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='data_contratacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
